import type { Metadata } from 'next'
import HeaderComponent from '@/components/HeaderComponent'
import './globals.css'
import AppMain from './container/AppMain'
import { PJS_Font } from './fonts'



export const metadata: Metadata = {
  title: 'Indonesia Comic Con Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={PJS_Font.className}>
        <AppMain>
          {children}
        </AppMain>
      </body>
    </html>
  )
}
